name: CI

on:
  push:
    branches:
      - main  # Chạy workflow khi có thay đổi trên nhánh main
  pull_request:
    branches:
      - main  # Chạy workflow khi có pull request tới nhánh main

jobs:
  build:

    runs-on: ubuntu-latest  # Sử dụng Ubuntu làm môi trường chạy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'  # Phiên bản Java bạn đang sử dụng

    - name: Build with Maven
      run: mvn clean install  # Chạy lệnh để biên dịch dự án

    - name: Run Tests
      run: mvn test  # Chạy các bài kiểm thử
